# -*- coding: utf-8 -*-
"""portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_f4eWC7cjCWT7sBN8VC_e0FP5CZdaoif

#**Exploring Global GDP per Capita**
##An exploratory analysis of GDP per capita estimates from the IMF, United Nations and World Bank, investigating data quality, statistical distributions, regional differences and extreme values.
##Python · Pandas · Matplotlib · Seaborn
"""

#uploanding dataset
from google.colab import files
uploaded = files.upload()

#importing libraries and reading the dataset
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("GDP (nominal) per Capita.csv",encoding= 'unicode_escape',  index_col=0)

"""##1. Exploring and preparing the Data"""

df.head(10)

df.info()

df['IMF_Year'].dtype

df['IMF_Year'].unique()

df['IMF_Year'].value_counts()

df['WorldBank_Year'].unique()

df['WorldBank_Year'].dtype

df['WorldBank_Year'].value_counts()

df['UN_Year'].unique()

df['UN_Year'].value_counts()

"""  After checking how many entries were available for each year and each organisation, as well as the data types of the year columns, I decided on the next steps to prepare the dataset for further analysis:

**1.** Clean the UN_Year column by converting "[n 10] 2021" to 2021.

**2.** Create a new DataFrame containing only the year with the highest coverage for each organisation.

  Based on the number of available entries, I selected:

  **IMF 2023**: representing 97% of its entries

  **UN 2021**: representing 95% of its entries
  
  **World Bank**: 2021, representing 89% of its entries
"""

# Convert UN_Year to string so we can remove '[n 10]'
df['UN_Year'] = df['UN_Year'].astype(str).str.replace('[n 10]', '', regex=False)
df['UN_Year'].value_counts()

#convert UN_Year to integer
df['UN_Year'] = df['UN_Year'].astype('Int64')
df['UN_Year'].dtype

df_filtered = df[
    (df['WorldBank_Year'] == 2021) &
    (df['UN_Year'] == 2021) &
    (df['IMF_Year'] == 2023)
]
df_filtered.head()

df_filtered = df_filtered[
    (df_filtered['UN_Region'] != 'World') &
    (~df_filtered['Country/Territory'].str.startswith('European Union', na=False))
].copy()

"""##2. Choosing the Right Statistic"""

# Checking some summary statistics for World Bank estimates
df_filtered['WorldBank_Estimate'].agg(
    ['min', 'max', 'median', 'mean']).round(2)

# Count how many countries are above the median
print(df_filtered[df_filtered['WorldBank_Estimate'] > 6228.00]['Country/Territory'].count())

# Count how many countries are below the median
print(df_filtered[df_filtered['WorldBank_Estimate'] < 6228.00]['Country/Territory'].count())

# Count how many countries are above the mean
print(df_filtered[df_filtered['WorldBank_Estimate'] > 15926.84]['Country/Territory'].count())

# Count how many countries are bellow the mean
print(df_filtered[df_filtered['WorldBank_Estimate'] < 15926.84]['Country/Territory'].count())

"""The code above shows how the distribution of GDP per capita across countries looks different depending on whether we use the mean or the median. Because of the large differences between the richest and poorest countries, a small number of very high values pull the mean upwards. As a result, many more countries fall below the mean than above it. For this reason, I will use the median as the main measure of central tendency in the following analysis."""

# Checking some summary statistics for IMF estimates
df_filtered['IMF_Estimate'].agg(
    ['min', 'max', 'median', 'mean']).round(2)

# Checking some summary statistics for UN estimates
df_filtered['UN_Estimate'].agg(
    ['min', 'max', 'median', 'mean']).round(2)

# Median for all three international organisations
df_filtered[['WorldBank_Estimate', 'IMF_Estimate', 'UN_Estimate']].median()

"""##2.1 Countries Below and Above the Median"""

#countries above median for WorldBank_Estimates
df_filtered[df_filtered['WorldBank_Estimate'] > 6357.00][['Country/Territory', 'WorldBank_Estimate']]

##countries below median for WorldBank_Estimates
df_filtered[df_filtered['WorldBank_Estimate'] < 6357.00][['Country/Territory', 'WorldBank_Estimate']]

# histogram of countries above median
df_filtered[df_filtered['WorldBank_Estimate'] > 6357.00]['WorldBank_Estimate'].hist(
    bins=[6357, 30000, 60000, 90000, 120000, 150000],
    figsize=(8, 5),
    color='mediumpurple',
    edgecolor='black'
)

plt.xlabel('GDP per capita')
plt.ylabel('Number of countries')
plt.title('Countries Above the Median GDP per Capita')

plt.show()

# histogram of countries bellow median

df_filtered[df_filtered['WorldBank_Estimate'] < 6357.00]['WorldBank_Estimate'].hist(
    bins=[0, 1500, 3000, 4500, 6500],
    figsize=(8, 5),
    color='salmon',
    edgecolor='black'
)

plt.xlabel('GDP per capita')
plt.ylabel('Number of countries')
plt.title('Countries Above the Median GDP per Capita')

plt.show()

# scatterplot with all countries
plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_filtered.sort_values('UN_Estimate', ascending = True),
    x='Country/Territory',
    y='UN_Estimate',
    color = '#2F6B4F'
)

plt.xticks([])
plt.title("UN Estimate by Country")


plt.show()

# Scatterplot for countries above median

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_filtered[df_filtered['IMF_Estimate'] > 7058.00].sort_values('IMF_Estimate'),
    x='Country/Territory',
    y='UN_Estimate',
    color = '#2F6B4F'
)

plt.xticks([])
plt.title("UN Estimate by Country (IMF Estimate > Median)")
plt.show()

# Scatterplot for countries above median

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_filtered[df_filtered['IMF_Estimate'] < 7058.00].sort_values('IMF_Estimate'),
    x='Country/Territory',
    y='UN_Estimate',
    color = 'salmon'
)

plt.xticks([])
plt.title("UN Estimate by Country (IMF Estimate < Median)")
plt.show()

"""##3. GDP per Capita by Region



"""

#number of countries by region
df_filtered['UN_Region'].value_counts()

#Scatter plot to show the distribution of countries by region and GDP per capita

df_sorted = df_filtered[df_filtered['UN_Region'] != 'World'].sort_values('IMF_Estimate', ascending=True)
plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_sorted,
    x='Country/Territory',
    y='IMF_Estimate',
    hue='UN_Region'
)

plt.xticks([])
plt.title("IMF Estimate by Country and Region")
plt.legend(title="Region")

plt.show()

#summary_stats
summary_stats = df_filtered.groupby('UN_Region')['WorldBank_Estimate'].agg(['min', 'max', 'median', 'mean']).round(2)
summary_stats

Europe_median = df_filtered[df_filtered['UN_Region'] == 'Europe']['WorldBank_Estimate'].median()
print(f"The median GDP per capita in Europe is {Europe_median} by World Bank")

# Bar chart for comparing the medians across regions
regional_medians = (
    df_filtered[df_filtered['UN_Region'] != 'World']
    .groupby('UN_Region')['WorldBank_Estimate']
    .median().sort_values(ascending=True)
)

region_colors = {
    'Africa': '#4C72B0',    # blue
    'Asia': '#DD8452',      # orange
    'Oceania': '#55A868',   # green
    'Americas': '#C44E52',  # red
    'Europe': '#8172B3',    # purple
}

regional_medians.plot(
    kind='bar',
    figsize=(8, 5),
    color=[region_colors[region] for region in regional_medians.index],

)

plt.xlabel('Region')
plt.ylabel('Median GDP per capita')
plt.title('Median GDP per Capita by Region')
plt.xticks(rotation=45)

plt.show()

region_colors = {
    'Africa': '#4C72B0',    # blue
    'Asia': '#DD8452',      # orange
    'Oceania': '#55A868',   # green
    'Americas': '#C44E52',  # red
    'Europe': '#8172B3',    # purple
}

df_plot = df_filtered[df_filtered['UN_Region'] != 'World'].sort_values('IMF_Estimate', ascending=True)

plt.figure(figsize=(10,6))
df_plot.plot(x='UN_Region', y='IMF_Estimate', kind='scatter',
        figsize=(10,6),
        title="Distribution of countries by Region and GDP",
        color =[region_colors[region] for region in df_plot['UN_Region']])




plt.show()

"""##3.1 Zooming in on Europe"""

#Countries in Europe
df_Europe = df_filtered[df_filtered['UN_Region'] == 'Europe']
df_Europe[['Country/Territory','IMF_Estimate']]

# Number of countries
print(f"There are {df_Europe['Country/Territory'].count()} countries in Europe")

#Countries in Europe above median by World Bank
df_Europe[df_Europe['WorldBank_Estimate'] > Europe_median][['Country/Territory', 'WorldBank_Estimate']]

#Countries in Europe below median by World Bank
df_Europe[df_Europe['WorldBank_Estimate'] < Europe_median][['Country/Territory', 'WorldBank_Estimate']]

#Countries by GDP per Capita in Europe

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_filtered[df_filtered['UN_Region'] == 'Europe'],
    x='Country/Territory',
    y='WorldBank_Estimate',
    color = '#8172B3'
)
plt.title("UN Estimate in Europe")
plt.xticks(rotation=90)
plt.show()

df_Europe['WorldBank_Estimate'].hist(
    bins = [0, 20000, 40000, 60000, 80000, 100000, 120000, 140000],
    figsize=(12, 7),
    color='#8172B3',
    edgecolor='black'
)

plt.xlabel('GDP intervals')
plt.ylabel('Number of countries')
plt.title('European Countries per GDP intervals')

plt.show()

"""Based on the tables and graphs above, we can see that only a few European countries have a very high GDP per capita. For example, the last graph shows that only four countries have a GDP per capita above $100,000, while most countries are concentrated closer to the European median.

##3.2 UK in Europe
"""

## Which countries in Europe has higher GDP than UK?
uk_gdp = df_Europe[
    df_Europe['Country/Territory'] == 'United Kingdom'
]['IMF_Estimate'].iloc[0]

print(f"UK GDP per capita: {uk_gdp}")

#European countries with GDP higher than UK
df_Europe[df_Europe['IMF_Estimate'] > uk_gdp][['Country/Territory', 'IMF_Estimate']]

#European countries with GDP lower than UK
df_Europe[df_Europe['IMF_Estimate'] < uk_gdp][['Country/Territory', 'IMF_Estimate']]

#Scatter Spot with countries below and above UK GDP

uk_gdp = df_Europe[
    df_Europe['Country/Territory'] == 'United Kingdom'
]['IMF_Estimate'].iloc[0]

colors = [
    'gold' if country == 'United Kingdom'
    else 'green' if gdp > uk_gdp
    else 'purple'
    for country, gdp in zip(
        df_Europe['Country/Territory'],
        df_Europe['IMF_Estimate']
    )
]

plt.figure(figsize=(16,10))

plt.scatter(
    df_Europe['Country/Territory'],
    df_Europe['IMF_Estimate'],
    c=colors,
    s=100
)

plt.title('European Countries by GDP per Capita')

plt.axhline(uk_gdp, linestyle='--')

plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""##4 Outliers in Europe"""

# Boxplot showing the outliers
sns.boxplot(x=df_Europe["IMF_Estimate"])

plt.show()

df_Europe[df_Europe['IMF_Estimate'] > 102000]['Country/Territory']

"""##5 Global View"""

import plotly.express as px

fig = px.choropleth(
    df_filtered,
    locations='Country/Territory',
    locationmode='country names',
    color='IMF_Estimate',
    hover_name='Country/Territory',
    title='World GDP per Capita',
    width=1000, # Adjusting the width of the map
    height=600  # Adjusting the height of the map
)

fig.show()

import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

# Select the GDP per capita values
gdp = df_filtered['WorldBank_Estimate'].dropna()

# Calculate mean and median
mean_gdp = gdp.mean()
median_gdp = gdp.median()

# Create histogram
plt.figure(figsize=(10, 6))

plt.hist(
    gdp,
    bins=25,
    color='#C8B6E2',   # light purple
    edgecolor='white'
)

# Mean line
plt.axvline(
    mean_gdp,
    color='#E6A23C',
    linestyle='--',
    linewidth=2.5,
    label=f'Mean: ${mean_gdp:,.0f}'
)

# Median line
plt.axvline(
    median_gdp,
    color='#4F8A8B',
    linestyle='-',
    linewidth=2.5,
    label=f'Median: ${median_gdp:,.0f}'
)

# Titles and labels
plt.title(
    'Distribution of GDP per Capita',
    fontsize=16,
    fontweight='bold'
)

plt.xlabel('GDP per capita (US$)', fontsize=12)
plt.ylabel('Number of countries', fontsize=12)

# Format x-axis as dollars
plt.gca().xaxis.set_major_formatter(
    FuncFormatter(lambda x, _: f'${x:,.0f}')
)

plt.legend(frameon=False)

plt.tight_layout()
plt.show()